#!/usr/bin/env bash
# Shared helpers for generated simulator run scripts.
# Generated by tools/gen_filelist.py — do not edit.

EDA_VIEWS="integration full_campaign soc_manifest soc_manifest_scale chip_top_example"

eda_prefix() {
  local view="$1"
  case "$view" in
    integration) echo "filelists/eda/work/integration" ;;
    full_campaign) echo "filelists/eda/test/full_campaign" ;;
    soc_manifest) echo "filelists/eda/test/soc_manifest" ;;
    soc_manifest_scale) echo "filelists/eda/test/soc_manifest_scale" ;;
    chip_top_example) echo "filelists/eda/test/chip_top_example" ;;
    integration_dut) echo "filelists/eda/work/integration" ;;
    *)
      echo "[eda] unknown view: $view" >&2
      echo "[eda] views: $EDA_VIEWS" >&2
      return 1 ;;
  esac
}

eda_require_view() {
  local view="$1"
  local p
  p="$(eda_prefix "$view")" || return 1
  if [[ ! -f "$p/manifest.list" ]]; then
    echo "[eda] missing $p/manifest.list — run: ./example.sh gen" >&2
    return 1
  fi
}


eda_top() {
  cat "$(eda_prefix "$1")/top.txt"
}

eda_vcd() {
  local f
  f="$(eda_prefix "$1")/vcd.txt"
  if [[ -f "$f" ]]; then cat "$f"; fi
}

eda_has_tb() {
  local f="$(eda_prefix "$1")/tb_top.list"
  grep -qvE "^#|^$" "$f" 2>/dev/null
}

# Emit -f flags for iverilog / tools that accept file lists directly.
eda_iverilog_f_flags() {
  local view="$1" p
  p="$(eda_prefix "$view")"
  for f in incdirs.list defines.list vcpu.list rtl.list tb_top.list; do
    [[ -f "$p/$f" ]] || continue
    grep -qvE "^#|^$" "$p/$f" 2>/dev/null || continue
    printf -- "-f %s/%s " "$p" "$f"
  done
}

# Source .v paths (one per line) from vcpu + rtl + tb_top lists.
eda_source_files() {
  local view="$1" p f line
  p="$(eda_prefix "$view")"
  for f in vcpu.list rtl.list tb_top.list; do
    [[ -f "$p/$f" ]] || continue
    while IFS= read -r line; do
      [[ "$line" =~ ^# ]] && continue
      [[ -z "$line" ]] && continue
      [[ "$line" == +* ]] && continue
      printf "%s\n" "$line"
    done < "$p/$f"
  done
}

# +incdir+ → -I for Verilator.
eda_verilator_incdirs() {
  local view="$1" p line
  p="$(eda_prefix "$view")/incdirs.list"
  [[ -f "$p" ]] || return 0
  while IFS= read -r line; do
    [[ "$line" =~ ^\+incdir\+ ]] || continue
    printf -- "-I%s " "${line#+incdir+}"
  done < "$p"
}

# +define+NAME → -DNAME for Verilator.
eda_verilator_defines() {
  local view="$1" p line name
  p="$(eda_prefix "$view")/defines.list"
  [[ -f "$p" ]] || return 0
  while IFS= read -r line; do
    [[ "$line" =~ ^\+define\+ ]] || continue
    name="${line#+define+}"
    printf -- "-D%s " "$name"
  done < "$p"
}

