// Work — VCPU IP (core + pool + orchestrator + agent)
// iverilog: iverilog -g2012 -f filelists/incdirs.f -f filelists/work/vcpu.f
// Generated by tools/gen_filelist.py — do not edit
// Paths relative to verif_cpu_verilog/ (package root)

rtl/verif_cpu_bus.v
rtl/verif_cpu_unified_pool.v
rtl/verif_cpu_txn_recorder.v
rtl/verif_cpu_core.v
rtl/verif_orchestrator.v
rtl/verif_agent.v
rtl/verif_cpu_sync.v

