// Verdi / SimVision combined import — mirrors filelists/work/rtl.f
// Top: verif_vcpu_soc_cell
// Generated by tools/gen_filelist.py — do not edit
// Usage (package root):  verdi -sv -f filelists/verdi_<view>.f -top <top>

+incdir+include
+incdir+firmware/campaign/include

// Work — real SoC attach (vcpu + bridges + soc_cell + connect VH)
// iverilog: iverilog -g2012 -f filelists/incdirs.f -f filelists/work/rtl.f

rtl/verif_cpu_bus.v
rtl/verif_cpu_unified_pool.v
rtl/verif_cpu_txn_recorder.v
rtl/verif_cpu_core.v
rtl/verif_orchestrator.v
rtl/verif_agent.v
rtl/verif_cpu_sync.v
rtl/verif_cpu_hw_force.v
rtl/verif_apb2_master.v
rtl/verif_apb_master.v
rtl/verif_apb4_master.v
rtl/verif_apb5_master.v
rtl/verif_ahb_lite_master.v
rtl/verif_ahb5_lite_master.v
rtl/verif_ahb_master.v
rtl/verif_axi_lite_master.v
rtl/verif_axi_full_master.v
rtl/verif_apb2_slave_simple.v
rtl/verif_apb_slave_simple.v
rtl/verif_ahb_lite_slave_simple.v
rtl/verif_axi_full_slave_simple.v
rtl/verif_vcpu_soc_cell.v

// --- generated headers (iverilog: -I include; compile deps) ---
// include/verif_soc_bus_connect.vh
// include/verif_amba_connect_macros.vh
