+libext+.v+.sv+.vh+.svh
+incdir+/home/user/tools/CodeFromAI/hc_hierarchy/design/unified_verify/include
+incdir+/home/user/tools/CodeFromAI/hc_hierarchy/design/unified_verify/rtl/hfa
+incdir+/home/user/tools/CodeFromAI/hc_hierarchy/design/unified_verify
+define+ENABLE=1
+define+HC_VERIFY=1
+define+USE_ALT=1
+define+USE_M1=1
-y /home/user/tools/CodeFromAI/hc_hierarchy/design/unified_verify/lib
/home/user/tools/CodeFromAI/hc_hierarchy/design/unified_verify/rtl/leaf_cell.v
/home/user/tools/CodeFromAI/hc_hierarchy/design/unified_verify/rtl/leaf_bind.v
/home/user/tools/CodeFromAI/hc_hierarchy/design/unified_verify/rtl/leaf_macro.v
/home/user/tools/CodeFromAI/hc_hierarchy/design/unified_verify/rtl/hfa/sub_module.v
/home/user/tools/CodeFromAI/hc_hierarchy/design/unified_verify/rtl/hfa/middle_module.v
/home/user/tools/CodeFromAI/hc_hierarchy/design/unified_verify/rtl/hfa/test_file.v
/home/user/tools/CodeFromAI/hc_hierarchy/design/unified_verify/rtl/hfa/top_module.v
/home/user/tools/CodeFromAI/hc_hierarchy/design/unified_verify/rtl/pkg_verify.sv
/home/user/tools/CodeFromAI/hc_hierarchy/design/unified_verify/rtl/bus_if.sv
/home/user/tools/CodeFromAI/hc_hierarchy/design/unified_verify/rtl/dup_a.v
/home/user/tools/CodeFromAI/hc_hierarchy/design/unified_verify/rtl/dup_b.v
/home/user/tools/CodeFromAI/hc_hierarchy/design/unified_verify/rtl/param_child.v
/home/user/tools/CodeFromAI/hc_hierarchy/design/unified_verify/rtl/defparam_top.v
/home/user/tools/CodeFromAI/hc_hierarchy/design/unified_verify/rtl/mid_arr.v
/home/user/tools/CodeFromAI/hc_hierarchy/design/unified_verify/rtl/mid_ifdef.v
/home/user/tools/CodeFromAI/hc_hierarchy/design/unified_verify/rtl/mid_gen_soc.v
/home/user/tools/CodeFromAI/hc_hierarchy/design/unified_verify/rtl/mid_gen_if.v
/home/user/tools/CodeFromAI/hc_hierarchy/design/unified_verify/rtl/mid_param.v
/home/user/tools/CodeFromAI/hc_hierarchy/design/unified_verify/rtl/inc_gate.v
/home/user/tools/CodeFromAI/hc_hierarchy/design/unified_verify/rtl/ecc_engine.v
/home/user/tools/CodeFromAI/hc_hierarchy/design/unified_verify/rtl/sub_bind.v
/home/user/tools/CodeFromAI/hc_hierarchy/design/unified_verify/rtl/top_verify.v
