// Full campaign TB — VerifCPU cores + SimpleSoC + platform agents
// Authoritative verification: iverilog simulation + VCD (see demo_full_campaign.py)
// Scenario steps: tb_full_campaign_gen.vh CAMPAIGN_EXECUTE (generated by example.sh gen)
//
// EDA interactive console (VCS/Xcelium UCLI — not iverilog):
//   simv +console_pause -ucli -do scripts/vcs/console_probe.tcl
//   call tb_full_campaign.console_cmd(4'd1, "vsync", 32'd10, 0, 0)
//   call tb_full_campaign.console_sync_cmd("sync_configure", 32'd10, 32'd7, 0)
// iverilog/vvp is batch-only; Ctrl+C terminates (no interactive call console).

`timescale 1ns/1ps
`include "verif_cpu_defs.vh"
`include "verif_platform_defs.vh"
`include "verif_verdict_policy.vh"
`include "campaign_params.vh"
`include "campaign_scale.vh"
`include "campaign_soc_platform.vh"
`include "campaign_manifest.vh"
`include "icode_map.vh"
`include "icode_bind.vh"
`include "verif_sim_watchdog.vh"

module tb_full_campaign;

  localparam integer TB_EXPECTED_PASS = 43;

  `VERIF_SIM_WATCHDOG_NS

  localparam OFF_A            = 32'h000;
  localparam OFF_B            = 32'h100;
  localparam OFF_C            = 32'h200;
  localparam OFF_SYNC         = 32'h380;
  localparam OFF_UART_HANG    = 32'hC00;
  localparam OFF_UART_RECOVER = 32'hD00;
  localparam FW_SIZE          = 32'h2000;
  localparam NUM_AGENTS       = `CAMPAIGN_MAX_SLOTS;
  localparam SL_AGENT_BANK    = (`CAMPAIGN_MAX_SLOTS == 0) ? 1 : `CAMPAIGN_MAX_SLOTS;
  localparam ICODE_POOL_SZ    = `ICODE_POOL_BYTES;

  wire [1:0]  orch_phase;
  wire [31:0] orch_boot_fw;
  wire        orch_reset;
  wire [31:0] orch_reset_count;

  wire [31:0] mstr_slot_count;
  wire [31:0] mstr_pass;
  wire [31:0] mstr_fail;
  wire [31:0] mstr_txns;

  wire [31:0] sl_slot_count [0:SL_AGENT_BANK-1];
  wire [31:0] sl_pass       [0:SL_AGENT_BANK-1];
  wire [31:0] sl_fail       [0:SL_AGENT_BANK-1];
  wire [31:0] sl_txns       [0:SL_AGENT_BANK-1];

  verif_orchestrator u_orch (
    .phase(orch_phase),
    .boot_fw_offset(orch_boot_fw),
    .reset_pulse(orch_reset),
    .reset_count(orch_reset_count)
  );

  simple_soc u_soc ();
  verif_soc_bus u_soc_bus ();
  verif_cpu_sync #(.MAX_SYNC_IDS(64), .MAX_CPUS(64)) u_sync ();
  verif_cpu_hw_force #(.MAX_ENTRIES(64)) u_hw_force ();

  `include "tb_full_campaign_gen.vh"

  verif_cpu_unified_pool #(.MEM_WORDS(`CAMPAIGN_MEM_WORDS)) u_pool ();

  `CAMPAIGN_MASTER_INSTANCE

  reg [1024*8:1] icode_pool_path;
  reg [1024*8:1] log_dir;
  reg [1024*8:1] vcd_main;
  reg [1024*8:1] vcd_cpu;
  reg [31:0] rdata;
  reg [1:0]  rresp;
  reg [1:0]  rport;
  reg [31:0] rec_before;
  integer step, max_s, ai, total_pass, total_fail;
  reg [31:0] check_pass;
  reg [31:0] check_fail;
  reg [31:0] hang_rec;
  reg [31:0] orch_rst_before;
  reg [31:0] vcd_marker;
  reg [31:0] pool_word;
  reg        pool_err;
  reg        icode_exec_ok;

  task check_eq;
    input [8*64:1] name;
    input        ok;
    begin
      if (ok) begin
        check_pass = check_pass + 1;
        $display("  [PASS] %0s", name);
      end else begin
        check_fail = check_fail + 1;
        $display("  [FAIL] %0s", name);
      end
    end
  endtask

  initial begin
    log_dir  = "logs/full_campaign";
    icode_pool_path = "firmware/campaign/build/icode_pool.bin";
    vcd_main = "sim_build/tb_full_campaign.vcd";

    $display("========================================================================");
    $display("tb_full_campaign: iverilog authoritative verification + VCD");
    $display("========================================================================");

    $dumpfile(vcd_main);
    $dumpvars(1, tb_full_campaign);
    $dumpvars(0, tb_full_campaign.u_orch);
    $dumpvars(0, tb_full_campaign.u_soc);
    $dumpvars(0, tb_full_campaign.g_ag[0].u_ag);
    $dumpvars(0, tb_full_campaign.g_ag[1].u_ag);
    $dumpvars(0, tb_full_campaign.g_ag[2].u_ag);

    check_pass = 0;
    check_fail = 0;

    `CAMPAIGN_EXECUTE

    $display("\n========================================================================");
    $display("CAMPAIGN REPORT (iverilog)");
    $display("========================================================================");
    `CAMPAIGN_REPORT_VCORES
    $display("  Agents PASS=%0d FAIL=%0d", total_pass, total_fail);
    $display("  Checklist: %0d passed / %0d failed", check_pass, check_fail);
    $display("  VCD: %0s", vcd_main);
    $display("========================================================================");

    `CAMPAIGN_CLOSE_VCORE_LOGS

    if (check_pass != TB_EXPECTED_PASS)
      $fatal(1, "tb_full_campaign: pass=%0d expected %0d", check_pass, TB_EXPECTED_PASS);
    if (check_fail != 0) begin
      vcd_marker = 32'hBADC0DE;
      $display("[FAIL] iverilog campaign — see checklist above.");
      $fatal(1);
    end
    vcd_marker = 32'hDEADDEAD;
    #1;
    $display("[SUCCESS] iverilog campaign passed — confirm via VCD: %0s", vcd_main);
    $finish;
  end

endmodule