# Auto-generated by gen_icodes_c.py — do not edit
# Mode: manifest (6 icode(s))
ICODE_SOURCES := sfr/check_sfr_ctrl.c sfr/check_sfr_mask.c sram/check_sram_marker.c sram/check_sram_aux.c uart/check_uart_baud.c uart/check_uart_irq.c
