// Test — internal regression (rtl + simple_soc + tb_full_campaign)
// iverilog: iverilog -g2012 -f filelists/incdirs.f -f filelists/test/tb_dut.f
// Generated by tools/gen_filelist.py — do not edit
// Paths relative to verif_cpu_verilog/ (package root)

rtl/verif_cpu_bus.v
rtl/verif_cpu_unified_pool.v
rtl/verif_cpu_txn_recorder.v
rtl/verif_cpu_core.v
rtl/verif_soc_bus.v
rtl/simple_soc.v
rtl/verif_orchestrator.v
rtl/verif_agent.v
rtl/verif_cpu_sync.v
rtl/verif_cpu_hw_force.v
tb/tb_full_campaign.v

// --- generated headers (iverilog: -I include; compile deps) ---
// include/campaign_params.vh
// include/campaign_scale.vh
// include/campaign_manifest.vh
// include/icode_map.vh
// include/icode_bind.vh
// include/campaign_soc_platform.vh
// include/soc_init_seq.vh
// include/verif_soc_bus_connect.vh
// include/tb_full_campaign_gen.vh
// firmware/full_campaign_unified.hex
// firmware/full_campaign_vcpu.hex
// firmware/campaign/build/icode_pool.bin
// firmware/campaign/build/full_campaign_vcpu.bin

