// Verdi / SimVision combined import — mirrors filelists/test/soc_manifest.f
// Top: tb_soc_manifest
// Generated by tools/gen_filelist.py — do not edit
// Usage (package root):  verdi -sv -f filelists/verdi_<view>.f -top <top>

+incdir+include
+incdir+firmware/campaign/include

// Test — bridge wiring reference (tb_soc_manifest)
// iverilog: iverilog -g2012 -f filelists/incdirs.f -f filelists/test/soc_manifest.f

+define+VERIF_MANIFEST_SOC_TB

rtl/verif_cpu_bus.v
rtl/verif_cpu_unified_pool.v
rtl/verif_cpu_txn_recorder.v
rtl/verif_cpu_core.v
rtl/verif_orchestrator.v
rtl/verif_agent.v
rtl/verif_cpu_sync.v
rtl/verif_apb2_master.v
rtl/verif_apb_master.v
rtl/verif_apb4_master.v
rtl/verif_apb5_master.v
rtl/verif_ahb_lite_master.v
rtl/verif_ahb5_lite_master.v
rtl/verif_ahb_master.v
rtl/verif_axi_lite_master.v
rtl/verif_axi_full_master.v
rtl/verif_apb2_slave_simple.v
rtl/verif_apb_slave_simple.v
rtl/verif_ahb_lite_slave_simple.v
rtl/verif_axi_full_slave_simple.v
rtl/verif_vcpu_soc_cell.v
tb/tb_soc_manifest.v

// --- generated headers (iverilog: -I include; compile deps) ---
// include/campaign_params.vh
// include/campaign_scale.vh
// include/campaign_manifest.vh
// include/icode_map.vh
// include/icode_bind.vh
// include/campaign_soc_platform.vh
// include/soc_init_seq.vh
// include/verif_soc_bus_connect.vh
// include/tb_soc_manifest_defs.vh
// include/tb_soc_manifest_gen.vh
// include/tb_soc_manifest_decode.vh
// include/verif_manifest_soc_bus_read.vh
// include/verif_manifest_soc_bus_write.vh
// firmware/full_campaign_unified.hex
// firmware/full_campaign_vcpu.hex
// firmware/campaign/build/icode_pool.bin
// firmware/campaign/build/full_campaign_vcpu.bin
