// Auto-generated by gen_soc_cell_rtl.py — do not edit
`timescale 1ns/1ps
`include "verif_bus_defs.vh"

// Dispatcher — pick cell module from manifest bus_type (see gen_tb_campaign.py)
module verif_vcpu_soc_cell #(
  parameter integer CPU_ID = 1,
  parameter [8*16:1] BUS_TYPE = "axi4lite"
)();
  initial begin
    $fatal(1, "verif_vcpu_soc_cell: use verif_vcpu_soc_cell_<bus_type> or generated g_slv[].u_bus");
  end
endmodule

// Implemented cell variants: apb2, apb3, apb4, apb5, ahb_lite, ahb5_lite, ahb, axi4lite, axi3full, axi4full, axi5full

// AHB (multi-master) — VCPU + bridge (connect VH: g_slv[cpu_id-1].u_bus.u_bridge)
module verif_vcpu_soc_cell_ahb #(
  parameter integer CPU_ID = 1
) (
  input  wire HCLK,
  input  wire HRESETn,
  output wire [31:0] HADDR,
  output wire [2:0]  HSIZE,
  output wire [1:0]  HTRANS,
  output wire [2:0]  HBURST,
  output wire        HPROT,
  output wire        HMASTLOCK,
  output wire        HWRITE,
  output wire [31:0] HWDATA,
  output wire        HNONSEC,
  output wire        HEXCL,
  input wire [31:0] HRDATA,
  input wire        HREADY,
  input wire [1:0]  HRESP,
  input wire        HEXOK,
  output wire        snoop_valid,
  output wire        snoop_wr,
  output wire [31:0] snoop_addr,
  output wire [31:0] snoop_data
);
  verif_ahb_master u_bridge (
    .HCLK(HCLK), .HRESETn(HRESETn),
    .HADDR(HADDR),
    .HSIZE(HSIZE),
    .HTRANS(HTRANS),
    .HBURST(HBURST),
    .HPROT(HPROT),
    .HMASTLOCK(HMASTLOCK),
    .HWRITE(HWRITE),
    .HWDATA(HWDATA),
    .HNONSEC(HNONSEC),
    .HEXCL(HEXCL),
    .HRDATA(HRDATA),
    .HREADY(HREADY),
    .HRESP(HRESP),
    .HEXOK(HEXOK),
    .snoop_valid(snoop_valid),
    .snoop_wr(snoop_wr),
    .snoop_addr(snoop_addr),
    .snoop_data(snoop_data)
  );

  verif_cpu_core #(
    .CPU_ID(CPU_ID),
    .USE_SHARED_BUS(0),
    .USE_SHARED_POOL(0),
    .USE_SOC_BUS(0),
    .USE_MANIFEST_SOC_BUS(1)
  ) u_cpu (
    .final_pc(),
    .total_steps(),
    .sim_stop(),
    .assert_pass(),
    .assert_fail(),
    .bus_txn_count(),
    .unique_pcs(),
    .recovery_count(),
    .trace_depth_out(),
    .instr_steps_traced()
  );

endmodule

// AHB5-Lite — VCPU + bridge (connect VH: g_slv[cpu_id-1].u_bus.u_bridge)
module verif_vcpu_soc_cell_ahb5_lite #(
  parameter integer CPU_ID = 1
) (
  input  wire HCLK,
  input  wire HRESETn,
  output wire [31:0] HADDR,
  output wire [2:0]  HSIZE,
  output wire [1:0]  HTRANS,
  output wire        HWRITE,
  output wire [31:0] HWDATA,
  output wire        HNONSEC,
  output wire        HEXCL,
  input wire [31:0] HRDATA,
  input wire        HREADY,
  input wire [1:0]  HRESP,
  input wire        HEXOK,
  output wire        snoop_valid,
  output wire        snoop_wr,
  output wire [31:0] snoop_addr,
  output wire [31:0] snoop_data
);
  verif_ahb5_lite_master u_bridge (
    .HCLK(HCLK), .HRESETn(HRESETn),
    .HADDR(HADDR),
    .HSIZE(HSIZE),
    .HTRANS(HTRANS),
    .HWRITE(HWRITE),
    .HWDATA(HWDATA),
    .HNONSEC(HNONSEC),
    .HEXCL(HEXCL),
    .HRDATA(HRDATA),
    .HREADY(HREADY),
    .HRESP(HRESP),
    .HEXOK(HEXOK),
    .snoop_valid(snoop_valid),
    .snoop_wr(snoop_wr),
    .snoop_addr(snoop_addr),
    .snoop_data(snoop_data)
  );

  verif_cpu_core #(
    .CPU_ID(CPU_ID),
    .USE_SHARED_BUS(0),
    .USE_SHARED_POOL(0),
    .USE_SOC_BUS(0),
    .USE_MANIFEST_SOC_BUS(1)
  ) u_cpu (
    .final_pc(),
    .total_steps(),
    .sim_stop(),
    .assert_pass(),
    .assert_fail(),
    .bus_txn_count(),
    .unique_pcs(),
    .recovery_count(),
    .trace_depth_out(),
    .instr_steps_traced()
  );

endmodule

// AHB-Lite — VCPU + bridge (connect VH: g_slv[cpu_id-1].u_bus.u_bridge)
module verif_vcpu_soc_cell_ahb_lite #(
  parameter integer CPU_ID = 1
) (
  input  wire HCLK,
  input  wire HRESETn,
  output wire [31:0] HADDR,
  output wire [2:0]  HSIZE,
  output wire [1:0]  HTRANS,
  output wire        HWRITE,
  output wire [31:0] HWDATA,
  input wire [31:0] HRDATA,
  input wire        HREADY,
  input wire [1:0]  HRESP,
  output wire        snoop_valid,
  output wire        snoop_wr,
  output wire [31:0] snoop_addr,
  output wire [31:0] snoop_data
);
  verif_ahb_lite_master u_bridge (
    .HCLK(HCLK), .HRESETn(HRESETn),
    .HADDR(HADDR),
    .HSIZE(HSIZE),
    .HTRANS(HTRANS),
    .HWRITE(HWRITE),
    .HWDATA(HWDATA),
    .HRDATA(HRDATA),
    .HREADY(HREADY),
    .HRESP(HRESP),
    .snoop_valid(snoop_valid),
    .snoop_wr(snoop_wr),
    .snoop_addr(snoop_addr),
    .snoop_data(snoop_data)
  );

  verif_cpu_core #(
    .CPU_ID(CPU_ID),
    .USE_SHARED_BUS(0),
    .USE_SHARED_POOL(0),
    .USE_SOC_BUS(0),
    .USE_MANIFEST_SOC_BUS(1)
  ) u_cpu (
    .final_pc(),
    .total_steps(),
    .sim_stop(),
    .assert_pass(),
    .assert_fail(),
    .bus_txn_count(),
    .unique_pcs(),
    .recovery_count(),
    .trace_depth_out(),
    .instr_steps_traced()
  );

endmodule

// APB2 — VCPU + bridge (connect VH: g_slv[cpu_id-1].u_bus.u_bridge)
module verif_vcpu_soc_cell_apb2 #(
  parameter integer CPU_ID = 1
) (
  input  wire PCLK,
  input  wire PRESETn,
  output wire [31:0] PADDR,
  output wire        PSEL,
  output wire        PENABLE,
  output wire        PWRITE,
  output wire [31:0] PWDATA,
  input wire [31:0] PRDATA,
  input wire        PREADY,
  output wire        snoop_valid,
  output wire        snoop_wr,
  output wire [31:0] snoop_addr,
  output wire [31:0] snoop_data
);
  verif_apb2_master u_bridge (
    .PCLK(PCLK), .PRESETn(PRESETn),
    .PADDR(PADDR),
    .PSEL(PSEL),
    .PENABLE(PENABLE),
    .PWRITE(PWRITE),
    .PWDATA(PWDATA),
    .PRDATA(PRDATA),
    .PREADY(PREADY),
    .snoop_valid(snoop_valid),
    .snoop_wr(snoop_wr),
    .snoop_addr(snoop_addr),
    .snoop_data(snoop_data)
  );

  verif_cpu_core #(
    .CPU_ID(CPU_ID),
    .USE_SHARED_BUS(0),
    .USE_SHARED_POOL(0),
    .USE_SOC_BUS(0),
    .USE_MANIFEST_SOC_BUS(1)
  ) u_cpu (
    .final_pc(),
    .total_steps(),
    .sim_stop(),
    .assert_pass(),
    .assert_fail(),
    .bus_txn_count(),
    .unique_pcs(),
    .recovery_count(),
    .trace_depth_out(),
    .instr_steps_traced()
  );

endmodule

// APB3 — VCPU + bridge (connect VH: g_slv[cpu_id-1].u_bus.u_bridge)
module verif_vcpu_soc_cell_apb3 #(
  parameter integer CPU_ID = 1
) (
  input  wire PCLK,
  input  wire PRESETn,
  output wire [31:0] PADDR,
  output wire        PSEL,
  output wire        PENABLE,
  output wire        PWRITE,
  output wire [31:0] PWDATA,
  output wire [3:0]  PSTRB,
  input wire [31:0] PRDATA,
  input wire        PREADY,
  input wire        PSLVERR,
  output wire        snoop_valid,
  output wire        snoop_wr,
  output wire [31:0] snoop_addr,
  output wire [31:0] snoop_data
);
  verif_apb_master u_bridge (
    .PCLK(PCLK), .PRESETn(PRESETn),
    .PADDR(PADDR),
    .PSEL(PSEL),
    .PENABLE(PENABLE),
    .PWRITE(PWRITE),
    .PWDATA(PWDATA),
    .PSTRB(PSTRB),
    .PRDATA(PRDATA),
    .PREADY(PREADY),
    .PSLVERR(PSLVERR),
    .snoop_valid(snoop_valid),
    .snoop_wr(snoop_wr),
    .snoop_addr(snoop_addr),
    .snoop_data(snoop_data)
  );

  verif_cpu_core #(
    .CPU_ID(CPU_ID),
    .USE_SHARED_BUS(0),
    .USE_SHARED_POOL(0),
    .USE_SOC_BUS(0),
    .USE_MANIFEST_SOC_BUS(1)
  ) u_cpu (
    .final_pc(),
    .total_steps(),
    .sim_stop(),
    .assert_pass(),
    .assert_fail(),
    .bus_txn_count(),
    .unique_pcs(),
    .recovery_count(),
    .trace_depth_out(),
    .instr_steps_traced()
  );

endmodule

// APB4 — VCPU + bridge (connect VH: g_slv[cpu_id-1].u_bus.u_bridge)
module verif_vcpu_soc_cell_apb4 #(
  parameter integer CPU_ID = 1
) (
  input  wire PCLK,
  input  wire PRESETn,
  output wire [31:0] PADDR,
  output wire        PSEL,
  output wire        PENABLE,
  output wire        PWRITE,
  output wire [31:0] PWDATA,
  output wire [3:0]  PSTRB,
  output wire [2:0]  PPROT,
  input wire [31:0] PRDATA,
  input wire        PREADY,
  input wire        PSLVERR,
  output wire        snoop_valid,
  output wire        snoop_wr,
  output wire [31:0] snoop_addr,
  output wire [31:0] snoop_data
);
  verif_apb4_master u_bridge (
    .PCLK(PCLK), .PRESETn(PRESETn),
    .PADDR(PADDR),
    .PSEL(PSEL),
    .PENABLE(PENABLE),
    .PWRITE(PWRITE),
    .PWDATA(PWDATA),
    .PSTRB(PSTRB),
    .PPROT(PPROT),
    .PRDATA(PRDATA),
    .PREADY(PREADY),
    .PSLVERR(PSLVERR),
    .snoop_valid(snoop_valid),
    .snoop_wr(snoop_wr),
    .snoop_addr(snoop_addr),
    .snoop_data(snoop_data)
  );

  verif_cpu_core #(
    .CPU_ID(CPU_ID),
    .USE_SHARED_BUS(0),
    .USE_SHARED_POOL(0),
    .USE_SOC_BUS(0),
    .USE_MANIFEST_SOC_BUS(1)
  ) u_cpu (
    .final_pc(),
    .total_steps(),
    .sim_stop(),
    .assert_pass(),
    .assert_fail(),
    .bus_txn_count(),
    .unique_pcs(),
    .recovery_count(),
    .trace_depth_out(),
    .instr_steps_traced()
  );

endmodule

// APB5 — VCPU + bridge (connect VH: g_slv[cpu_id-1].u_bus.u_bridge)
module verif_vcpu_soc_cell_apb5 #(
  parameter integer CPU_ID = 1
) (
  input  wire PCLK,
  input  wire PRESETn,
  output wire [31:0] PADDR,
  output wire        PSEL,
  output wire        PENABLE,
  output wire        PWRITE,
  output wire [31:0] PWDATA,
  output wire [3:0]  PSTRB,
  output wire [2:0]  PPROT,
  output wire        PWAKEUP,
  input wire [31:0] PRDATA,
  input wire        PREADY,
  input wire        PSLVERR,
  output wire        snoop_valid,
  output wire        snoop_wr,
  output wire [31:0] snoop_addr,
  output wire [31:0] snoop_data
);
  verif_apb5_master u_bridge (
    .PCLK(PCLK), .PRESETn(PRESETn),
    .PADDR(PADDR),
    .PSEL(PSEL),
    .PENABLE(PENABLE),
    .PWRITE(PWRITE),
    .PWDATA(PWDATA),
    .PSTRB(PSTRB),
    .PPROT(PPROT),
    .PWAKEUP(PWAKEUP),
    .PRDATA(PRDATA),
    .PREADY(PREADY),
    .PSLVERR(PSLVERR),
    .snoop_valid(snoop_valid),
    .snoop_wr(snoop_wr),
    .snoop_addr(snoop_addr),
    .snoop_data(snoop_data)
  );

  verif_cpu_core #(
    .CPU_ID(CPU_ID),
    .USE_SHARED_BUS(0),
    .USE_SHARED_POOL(0),
    .USE_SOC_BUS(0),
    .USE_MANIFEST_SOC_BUS(1)
  ) u_cpu (
    .final_pc(),
    .total_steps(),
    .sim_stop(),
    .assert_pass(),
    .assert_fail(),
    .bus_txn_count(),
    .unique_pcs(),
    .recovery_count(),
    .trace_depth_out(),
    .instr_steps_traced()
  );

endmodule

// AXI3 full — VCPU + bridge (connect VH: g_slv[cpu_id-1].u_bus.u_bridge)
module verif_vcpu_soc_cell_axi3full #(
  parameter integer CPU_ID = 1
  ,parameter integer AXI_PROT = 3
) (
  input  wire ACLK,
  input  wire ARESETn,
  output wire [3:0]  ARID,
  output wire [31:0] ARADDR,
  output wire [7:0]  ARLEN,
  output wire [2:0]  ARSIZE,
  output wire [2:0]  ARBURST,
  output wire        ARVALID,
  output wire        RREADY,
  output wire [3:0]  AWID,
  output wire [31:0] AWADDR,
  output wire [7:0]  AWLEN,
  output wire [2:0]  AWSIZE,
  output wire [2:0]  AWBURST,
  output wire        AWVALID,
  output wire [3:0]  WID,
  output wire [31:0] WDATA,
  output wire [3:0]  WSTRB,
  output wire        WLAST,
  output wire        WVALID,
  output wire        BREADY,
  input wire        ARREADY,
  input wire [3:0]  RID,
  input wire        RVALID,
  input wire [31:0] RDATA,
  input wire [1:0]  RRESP,
  input wire        RLAST,
  input wire        AWREADY,
  input wire        WREADY,
  input wire [3:0]  BID,
  input wire        BVALID,
  input wire [1:0]  BRESP,
  output wire        snoop_valid,
  output wire        snoop_wr,
  output wire [31:0] snoop_addr,
  output wire [31:0] snoop_data
);
  verif_axi_full_master #(.AXI_PROT(AXI_PROT)) u_bridge (
    .ACLK(ACLK), .ARESETn(ARESETn),
    .ARID(ARID),
    .ARADDR(ARADDR),
    .ARLEN(ARLEN),
    .ARSIZE(ARSIZE),
    .ARBURST(ARBURST),
    .ARVALID(ARVALID),
    .RREADY(RREADY),
    .AWID(AWID),
    .AWADDR(AWADDR),
    .AWLEN(AWLEN),
    .AWSIZE(AWSIZE),
    .AWBURST(AWBURST),
    .AWVALID(AWVALID),
    .WID(WID),
    .WDATA(WDATA),
    .WSTRB(WSTRB),
    .WLAST(WLAST),
    .WVALID(WVALID),
    .BREADY(BREADY),
    .ARREADY(ARREADY),
    .RID(RID),
    .RVALID(RVALID),
    .RDATA(RDATA),
    .RRESP(RRESP),
    .RLAST(RLAST),
    .AWREADY(AWREADY),
    .WREADY(WREADY),
    .BID(BID),
    .BVALID(BVALID),
    .BRESP(BRESP),
    .snoop_valid(snoop_valid),
    .snoop_wr(snoop_wr),
    .snoop_addr(snoop_addr),
    .snoop_data(snoop_data)
  );

  verif_cpu_core #(
    .CPU_ID(CPU_ID),
    .USE_SHARED_BUS(0),
    .USE_SHARED_POOL(0),
    .USE_SOC_BUS(0),
    .USE_MANIFEST_SOC_BUS(1)
  ) u_cpu (
    .final_pc(),
    .total_steps(),
    .sim_stop(),
    .assert_pass(),
    .assert_fail(),
    .bus_txn_count(),
    .unique_pcs(),
    .recovery_count(),
    .trace_depth_out(),
    .instr_steps_traced()
  );

endmodule

// AXI4 full — VCPU + bridge (connect VH: g_slv[cpu_id-1].u_bus.u_bridge)
module verif_vcpu_soc_cell_axi4full #(
  parameter integer CPU_ID = 1
  ,parameter integer AXI_PROT = 4
) (
  input  wire ACLK,
  input  wire ARESETn,
  output wire [3:0]  ARID,
  output wire [31:0] ARADDR,
  output wire [7:0]  ARLEN,
  output wire [2:0]  ARSIZE,
  output wire [2:0]  ARBURST,
  output wire [3:0]  ARQOS,
  output wire [3:0]  ARREGION,
  output wire        ARVALID,
  output wire        RREADY,
  output wire [3:0]  AWID,
  output wire [31:0] AWADDR,
  output wire [7:0]  AWLEN,
  output wire [2:0]  AWSIZE,
  output wire [2:0]  AWBURST,
  output wire [3:0]  AWQOS,
  output wire [3:0]  AWREGION,
  output wire [5:0]  AWATOP,
  output wire        AWVALID,
  output wire [3:0]  WID,
  output wire [31:0] WDATA,
  output wire [3:0]  WSTRB,
  output wire        WLAST,
  output wire        WVALID,
  output wire        BREADY,
  input wire        ARREADY,
  input wire [3:0]  RID,
  input wire        RVALID,
  input wire [31:0] RDATA,
  input wire [1:0]  RRESP,
  input wire        RLAST,
  input wire        AWREADY,
  input wire        WREADY,
  input wire [3:0]  BID,
  input wire        BVALID,
  input wire [1:0]  BRESP,
  output wire        snoop_valid,
  output wire        snoop_wr,
  output wire [31:0] snoop_addr,
  output wire [31:0] snoop_data
);
  verif_axi_full_master #(.AXI_PROT(AXI_PROT)) u_bridge (
    .ACLK(ACLK), .ARESETn(ARESETn),
    .ARID(ARID),
    .ARADDR(ARADDR),
    .ARLEN(ARLEN),
    .ARSIZE(ARSIZE),
    .ARBURST(ARBURST),
    .ARQOS(ARQOS),
    .ARREGION(ARREGION),
    .ARVALID(ARVALID),
    .RREADY(RREADY),
    .AWID(AWID),
    .AWADDR(AWADDR),
    .AWLEN(AWLEN),
    .AWSIZE(AWSIZE),
    .AWBURST(AWBURST),
    .AWQOS(AWQOS),
    .AWREGION(AWREGION),
    .AWATOP(AWATOP),
    .AWVALID(AWVALID),
    .WID(WID),
    .WDATA(WDATA),
    .WSTRB(WSTRB),
    .WLAST(WLAST),
    .WVALID(WVALID),
    .BREADY(BREADY),
    .ARREADY(ARREADY),
    .RID(RID),
    .RVALID(RVALID),
    .RDATA(RDATA),
    .RRESP(RRESP),
    .RLAST(RLAST),
    .AWREADY(AWREADY),
    .WREADY(WREADY),
    .BID(BID),
    .BVALID(BVALID),
    .BRESP(BRESP),
    .snoop_valid(snoop_valid),
    .snoop_wr(snoop_wr),
    .snoop_addr(snoop_addr),
    .snoop_data(snoop_data)
  );

  verif_cpu_core #(
    .CPU_ID(CPU_ID),
    .USE_SHARED_BUS(0),
    .USE_SHARED_POOL(0),
    .USE_SOC_BUS(0),
    .USE_MANIFEST_SOC_BUS(1)
  ) u_cpu (
    .final_pc(),
    .total_steps(),
    .sim_stop(),
    .assert_pass(),
    .assert_fail(),
    .bus_txn_count(),
    .unique_pcs(),
    .recovery_count(),
    .trace_depth_out(),
    .instr_steps_traced()
  );

endmodule

// AXI4-Lite — VCPU + bridge (connect VH: g_slv[cpu_id-1].u_bus.u_bridge)
module verif_vcpu_soc_cell_axi4lite #(
  parameter integer CPU_ID = 1
) (
  input  wire ACLK,
  input  wire ARESETn,
  output wire        ARVALID,
  output wire [31:0] ARADDR,
  output wire [2:0]  ARSIZE,
  output wire        RREADY,
  output wire        AWVALID,
  output wire [31:0] AWADDR,
  output wire [2:0]  AWSIZE,
  output wire        WVALID,
  output wire [31:0] WDATA,
  output wire [3:0]  WSTRB,
  output wire        BREADY,
  input wire        ARREADY,
  input wire        RVALID,
  input wire [31:0] RDATA,
  input wire [1:0]  RRESP,
  input wire        AWREADY,
  input wire        WREADY,
  input wire        BVALID,
  input wire [1:0]  BRESP,
  output wire        snoop_valid,
  output wire        snoop_wr,
  output wire [31:0] snoop_addr,
  output wire [31:0] snoop_data
);
  verif_axi_lite_master u_bridge (
    .ACLK(ACLK), .ARESETn(ARESETn),
    .ARVALID(ARVALID),
    .ARADDR(ARADDR),
    .ARSIZE(ARSIZE),
    .RREADY(RREADY),
    .AWVALID(AWVALID),
    .AWADDR(AWADDR),
    .AWSIZE(AWSIZE),
    .WVALID(WVALID),
    .WDATA(WDATA),
    .WSTRB(WSTRB),
    .BREADY(BREADY),
    .ARREADY(ARREADY),
    .RVALID(RVALID),
    .RDATA(RDATA),
    .RRESP(RRESP),
    .AWREADY(AWREADY),
    .WREADY(WREADY),
    .BVALID(BVALID),
    .BRESP(BRESP),
    .snoop_valid(snoop_valid),
    .snoop_wr(snoop_wr),
    .snoop_addr(snoop_addr),
    .snoop_data(snoop_data)
  );

  verif_cpu_core #(
    .CPU_ID(CPU_ID),
    .USE_SHARED_BUS(0),
    .USE_SHARED_POOL(0),
    .USE_SOC_BUS(0),
    .USE_MANIFEST_SOC_BUS(1)
  ) u_cpu (
    .final_pc(),
    .total_steps(),
    .sim_stop(),
    .assert_pass(),
    .assert_fail(),
    .bus_txn_count(),
    .unique_pcs(),
    .recovery_count(),
    .trace_depth_out(),
    .instr_steps_traced()
  );

endmodule

// AXI5 full — VCPU + bridge (connect VH: g_slv[cpu_id-1].u_bus.u_bridge)
module verif_vcpu_soc_cell_axi5full #(
  parameter integer CPU_ID = 1
  ,parameter integer AXI_PROT = 5
) (
  input  wire ACLK,
  input  wire ARESETn,
  output wire [3:0]  ARID,
  output wire [31:0] ARADDR,
  output wire [7:0]  ARLEN,
  output wire [2:0]  ARSIZE,
  output wire [2:0]  ARBURST,
  output wire [3:0]  ARQOS,
  output wire [3:0]  ARREGION,
  output wire        ARVALID,
  output wire        RREADY,
  output wire [3:0]  AWID,
  output wire [31:0] AWADDR,
  output wire [7:0]  AWLEN,
  output wire [2:0]  AWSIZE,
  output wire [2:0]  AWBURST,
  output wire [3:0]  AWQOS,
  output wire [3:0]  AWREGION,
  output wire [5:0]  AWATOP,
  output wire        AWVALID,
  output wire [3:0]  WID,
  output wire [31:0] WDATA,
  output wire [3:0]  WSTRB,
  output wire        WLAST,
  output wire        WVALID,
  output wire        BREADY,
  input wire        ARREADY,
  input wire [3:0]  RID,
  input wire        RVALID,
  input wire [31:0] RDATA,
  input wire [1:0]  RRESP,
  input wire        RLAST,
  input wire        AWREADY,
  input wire        WREADY,
  input wire [3:0]  BID,
  input wire        BVALID,
  input wire [1:0]  BRESP,
  output wire        snoop_valid,
  output wire        snoop_wr,
  output wire [31:0] snoop_addr,
  output wire [31:0] snoop_data
);
  verif_axi_full_master #(.AXI_PROT(AXI_PROT)) u_bridge (
    .ACLK(ACLK), .ARESETn(ARESETn),
    .ARID(ARID),
    .ARADDR(ARADDR),
    .ARLEN(ARLEN),
    .ARSIZE(ARSIZE),
    .ARBURST(ARBURST),
    .ARQOS(ARQOS),
    .ARREGION(ARREGION),
    .ARVALID(ARVALID),
    .RREADY(RREADY),
    .AWID(AWID),
    .AWADDR(AWADDR),
    .AWLEN(AWLEN),
    .AWSIZE(AWSIZE),
    .AWBURST(AWBURST),
    .AWQOS(AWQOS),
    .AWREGION(AWREGION),
    .AWATOP(AWATOP),
    .AWVALID(AWVALID),
    .WID(WID),
    .WDATA(WDATA),
    .WSTRB(WSTRB),
    .WLAST(WLAST),
    .WVALID(WVALID),
    .BREADY(BREADY),
    .ARREADY(ARREADY),
    .RID(RID),
    .RVALID(RVALID),
    .RDATA(RDATA),
    .RRESP(RRESP),
    .RLAST(RLAST),
    .AWREADY(AWREADY),
    .WREADY(WREADY),
    .BID(BID),
    .BVALID(BVALID),
    .BRESP(BRESP),
    .snoop_valid(snoop_valid),
    .snoop_wr(snoop_wr),
    .snoop_addr(snoop_addr),
    .snoop_data(snoop_data)
  );

  verif_cpu_core #(
    .CPU_ID(CPU_ID),
    .USE_SHARED_BUS(0),
    .USE_SHARED_POOL(0),
    .USE_SOC_BUS(0),
    .USE_MANIFEST_SOC_BUS(1)
  ) u_cpu (
    .final_pc(),
    .total_steps(),
    .sim_stop(),
    .assert_pass(),
    .assert_fail(),
    .bus_txn_count(),
    .unique_pcs(),
    .recovery_count(),
    .trace_depth_out(),
    .instr_steps_traced()
  );

endmodule
