// Auto-generated by gen_soc_cell_rtl.py — do not edit
`timescale 1ns/1ps
`include "verif_bus_defs.vh"

// AHB-Lite — VCPU + bridge (connect VH: g_slv[cpu_id-1].u_bus.u_bridge)
module verif_vcpu_soc_cell_ahb_lite #(
  parameter integer CPU_ID = 1
  ,parameter integer ADDR_WIDTH = 32
  ,parameter integer DATA_WIDTH = 32
) (
  input  wire HCLK,
  input  wire HRESETn,
  output wire [ADDR_WIDTH-1:0] HADDR,
  output wire [2:0]  HSIZE,
  output wire [1:0]  HTRANS,
  output wire        HWRITE,
  output wire [DATA_WIDTH-1:0] HWDATA,
  input wire [DATA_WIDTH-1:0] HRDATA,
  input wire        HREADY,
  input wire [1:0]  HRESP,
  output wire        snoop_valid,
  output wire        snoop_wr,
  output wire [31:0] snoop_addr,
  output wire [31:0] snoop_data
);
  verif_ahb_lite_master #(.ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH)) u_bridge (
    .HCLK(HCLK), .HRESETn(HRESETn),
    .HADDR(HADDR),
    .HSIZE(HSIZE),
    .HTRANS(HTRANS),
    .HWRITE(HWRITE),
    .HWDATA(HWDATA),
    .HRDATA(HRDATA),
    .HREADY(HREADY),
    .HRESP(HRESP),
    .snoop_valid(snoop_valid),
    .snoop_wr(snoop_wr),
    .snoop_addr(snoop_addr),
    .snoop_data(snoop_data)
  );

  verif_cpu_core #(
    .CPU_ID(CPU_ID),
    .USE_SHARED_BUS(0),
    .USE_SHARED_POOL(0),
    .USE_SOC_BUS(0),
    .USE_MANIFEST_SOC_BUS(1)
  ) u_cpu (
    .final_pc(),
    .total_steps(),
    .sim_stop(),
    .assert_pass(),
    .assert_fail(),
    .bus_txn_count(),
    .unique_pcs(),
    .recovery_count(),
    .trace_depth_out(),
    .instr_steps_traced()
  );

endmodule

// APB3 — VCPU + bridge (connect VH: g_slv[cpu_id-1].u_bus.u_bridge)
module verif_vcpu_soc_cell_apb3 #(
  parameter integer CPU_ID = 1
  ,parameter integer ADDR_WIDTH = 32
  ,parameter integer DATA_WIDTH = 32
) (
  input  wire PCLK,
  input  wire PRESETn,
  output wire [ADDR_WIDTH-1:0] PADDR,
  output wire        PSEL,
  output wire        PENABLE,
  output wire        PWRITE,
  output wire [DATA_WIDTH-1:0] PWDATA,
  output wire [DATA_WIDTH/8-1:0] PSTRB,
  input wire [DATA_WIDTH-1:0] PRDATA,
  input wire        PREADY,
  input wire        PSLVERR,
  output wire        snoop_valid,
  output wire        snoop_wr,
  output wire [31:0] snoop_addr,
  output wire [31:0] snoop_data
);
  verif_apb_master #(.ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH)) u_bridge (
    .PCLK(PCLK), .PRESETn(PRESETn),
    .PADDR(PADDR),
    .PSEL(PSEL),
    .PENABLE(PENABLE),
    .PWRITE(PWRITE),
    .PWDATA(PWDATA),
    .PSTRB(PSTRB),
    .PRDATA(PRDATA),
    .PREADY(PREADY),
    .PSLVERR(PSLVERR),
    .snoop_valid(snoop_valid),
    .snoop_wr(snoop_wr),
    .snoop_addr(snoop_addr),
    .snoop_data(snoop_data)
  );

  verif_cpu_core #(
    .CPU_ID(CPU_ID),
    .USE_SHARED_BUS(0),
    .USE_SHARED_POOL(0),
    .USE_SOC_BUS(0),
    .USE_MANIFEST_SOC_BUS(1)
  ) u_cpu (
    .final_pc(),
    .total_steps(),
    .sim_stop(),
    .assert_pass(),
    .assert_fail(),
    .bus_txn_count(),
    .unique_pcs(),
    .recovery_count(),
    .trace_depth_out(),
    .instr_steps_traced()
  );

endmodule

// AXI4-Lite — VCPU + bridge (connect VH: g_slv[cpu_id-1].u_bus.u_bridge)
module verif_vcpu_soc_cell_axi4lite #(
  parameter integer CPU_ID = 1
  ,parameter integer ADDR_WIDTH = 32
  ,parameter integer DATA_WIDTH = 32
) (
  input  wire ACLK,
  input  wire ARESETn,
  output wire        ARVALID,
  output wire [ADDR_WIDTH-1:0] ARADDR,
  output wire [2:0]  ARSIZE,
  output wire [2:0]  ARPROT,
  output wire        RREADY,
  output wire        AWVALID,
  output wire [ADDR_WIDTH-1:0] AWADDR,
  output wire [2:0]  AWSIZE,
  output wire [2:0]  AWPROT,
  output wire        WVALID,
  output wire [DATA_WIDTH-1:0] WDATA,
  output wire [DATA_WIDTH/8-1:0] WSTRB,
  output wire        BREADY,
  input wire        ARREADY,
  input wire        RVALID,
  input wire [DATA_WIDTH-1:0] RDATA,
  input wire [1:0]  RRESP,
  input wire        AWREADY,
  input wire        WREADY,
  input wire        BVALID,
  input wire [1:0]  BRESP,
  output wire        snoop_valid,
  output wire        snoop_wr,
  output wire [31:0] snoop_addr,
  output wire [31:0] snoop_data
);
  verif_axi_lite_master #(.ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH)) u_bridge (
    .ACLK(ACLK), .ARESETn(ARESETn),
    .ARVALID(ARVALID),
    .ARADDR(ARADDR),
    .ARSIZE(ARSIZE),
    .ARPROT(ARPROT),
    .RREADY(RREADY),
    .AWVALID(AWVALID),
    .AWADDR(AWADDR),
    .AWSIZE(AWSIZE),
    .AWPROT(AWPROT),
    .WVALID(WVALID),
    .WDATA(WDATA),
    .WSTRB(WSTRB),
    .BREADY(BREADY),
    .ARREADY(ARREADY),
    .RVALID(RVALID),
    .RDATA(RDATA),
    .RRESP(RRESP),
    .AWREADY(AWREADY),
    .WREADY(WREADY),
    .BVALID(BVALID),
    .BRESP(BRESP),
    .snoop_valid(snoop_valid),
    .snoop_wr(snoop_wr),
    .snoop_addr(snoop_addr),
    .snoop_data(snoop_data)
  );

  verif_cpu_core #(
    .CPU_ID(CPU_ID),
    .USE_SHARED_BUS(0),
    .USE_SHARED_POOL(0),
    .USE_SOC_BUS(0),
    .USE_MANIFEST_SOC_BUS(1)
  ) u_cpu (
    .final_pc(),
    .total_steps(),
    .sim_stop(),
    .assert_pass(),
    .assert_fail(),
    .bus_txn_count(),
    .unique_pcs(),
    .recovery_count(),
    .trace_depth_out(),
    .instr_steps_traced()
  );

endmodule
