# Auto-generated by gen_tb_campaign.py — chip_top tier-scoped RTL
# hierarchy: 3 slave(s), bus keys: ahb_lite, apb3, axi4lite
CHIP_BUS_RTL := rtl/verif_ahb_lite_master.v rtl/verif_ahb_lite_slave_simple.v rtl/verif_apb_master.v rtl/verif_apb_slave_simple.v rtl/verif_axi_full_slave_simple.v rtl/verif_axi_lite_master.v
CHIP_STUB_RTL :=
