// Auto-generated by build_icode_pool.py — do not edit
`ifndef ICODE_BIND_VH
`define ICODE_BIND_VH

`define ICODE_MSTR_SLOT0_PTR 32'h00001000
`define ICODE_MSTR_SLOT0_NAME "check_sfr_ctrl"
`define ICODE_MSTR_SLOT1_PTR 32'h00002000
`define ICODE_MSTR_SLOT1_NAME "check_sfr_mask"

`endif
