// Auto-generated by gen_tb_campaign.py — 60-slot scale integration TB
`ifndef TB_SOC_MANIFEST_SCALE_DEFS_VH
`define TB_SOC_MANIFEST_SCALE_DEFS_VH

`define SOC_MANIFEST_SCALE_NUM_WIRED 60
`define SOC_MANIFEST_SCALE_MAX_GI 60
`define SOC_MANIFEST_SCALE_LAST_GI 59
`define SOC_MANIFEST_SCALE_LAST_CELL_OK (g_slv59.u_bus.u_cpu.CPU_ID == 60)

`endif
