// Auto-generated by gen_tb_campaign.py — tb_soc_manifest bus_write bind
        case (CPU_ID)
          7'd0: tb_soc_manifest.g_slv-1.u_bus.u_bridge.bus_write(addr, data, size, resp);
          default: resp = 2'd2;
        endcase
