// Auto-generated by gen_soc_cell_rtl.py — SSOT: firmware/campaign/amba_bus_registry.py
`ifndef VERIF_BUS_SOC_WIDTHS_VH
`define VERIF_BUS_SOC_WIDTHS_VH
`define VERIF_ADDR_WIDTH 32
`define VERIF_DATA_WIDTH 32
`define VERIF_STRB_WIDTH (`VERIF_DATA_WIDTH / 8)
`define VERIF_AXI_ID_WIDTH 4
`define VERIF_AXI_MAX_OUTSTANDING 4
`endif
