// Auto-generated by gen_tb_campaign.py — tb_soc_manifest_scale bus_read_outstanding_count
        case (CPU_ID)
          7'd1: tb_soc_manifest_scale.g_slv0.u_bus.u_bridge.bus_read_outstanding_count(n);
          7'd2: tb_soc_manifest_scale.g_slv1.u_bus.u_bridge.bus_read_outstanding_count(n);
          7'd3: tb_soc_manifest_scale.g_slv2.u_bus.u_bridge.bus_read_outstanding_count(n);
          default: begin
            n = 0;
            $fatal(1, "[BUS] bus_*_count: unbound CPU_ID=%0d", CPU_ID);
          end
        endcase
