// Auto-generated by gen_tb_campaign.py — chip_top_example bus_write_wait
        case (CPU_ID)
          7'd1: chip_top_example.g_slv0.u_bus.u_bridge.bus_write_wait(handle, resp);
          7'd2: chip_top_example.g_slv1.u_bus.u_bridge.bus_write_wait(handle, resp);
          7'd3: chip_top_example.g_slv2.u_bus.u_bridge.bus_write_wait(handle, resp);
          default: begin
            resp = 2'd2;
            $fatal(1, "[BUS] bus_write_wait: unbound CPU_ID=%0d", CPU_ID);
          end
        endcase
