// Auto-generated by gen_tb_campaign.py — tb_soc_manifest bus_write_poll
        case (CPU_ID)
          7'd1: begin resp = 2'd2; done = 1'b0; end
          7'd2: begin resp = 2'd2; done = 1'b0; end
          7'd3: tb_soc_manifest.g_slv2.u_bus.u_bridge.bus_write_poll(handle, resp, done);
          default: begin resp = 2'd2; done = 1'b0; end
        endcase
