// Auto-generated by gen_tb_campaign.py — chip_top_example bus_read_wait
        case (CPU_ID)
          7'd1: begin data = 32'h0; resp = 2'd2; end
          7'd2: begin data = 32'h0; resp = 2'd2; end
          7'd3: chip_top_example.g_slv2.u_bus.u_bridge.bus_read_wait(handle, data, resp);
          default: begin data = 32'h0; resp = 2'd2; end
        endcase
