// Auto-generated by gen_tb_campaign.py — tb_soc_manifest bus_write_issue
        case (CPU_ID)
          7'd1: begin handle = -1; ok = 1'b0; end
          7'd2: begin handle = -1; ok = 1'b0; end
          7'd3: tb_soc_manifest.g_slv2.u_bus.u_bridge.bus_write_issue(addr, data, size, handle, ok);
          default: begin handle = -1; ok = 1'b0; end
        endcase
