// Auto-generated by gen_tb_campaign.py — chip_top_example bus_write_wait
        case (CPU_ID)
          7'd1: resp = 2'd2;
          7'd2: resp = 2'd2;
          7'd3: chip_top_example.g_slv2.u_bus.u_bridge.bus_write_wait(handle, resp);
          default: resp = 2'd2;
        endcase
