// Auto-generated by gen_tb_campaign.py — chip_top_example bus_read (VERIF_CHIP_SOC_TB)
        case (CPU_ID)
          7'd1: chip_top_example.g_slv0.u_bus.u_bridge.bus_read(addr, size, data, resp);
          7'd2: chip_top_example.g_slv1.u_bus.u_bridge.bus_read(addr, size, data, resp);
          7'd3: chip_top_example.g_slv2.u_bus.u_bridge.bus_read(addr, size, data, resp);
          7'd37: chip_top_example.g_slv36.u_bus.u_bridge.bus_read(addr, size, data, resp);
          default: begin data = 32'h0; resp = 2'd2; end
        endcase
