// Auto-generated by gen_tb_campaign.py — tb_soc_manifest_scale bus_read_wait
        case (CPU_ID)
          7'd1: tb_soc_manifest_scale.g_slv0.u_bus.u_bridge.bus_read_wait(handle, data, resp);
          7'd2: tb_soc_manifest_scale.g_slv1.u_bus.u_bridge.bus_read_wait(handle, data, resp);
          7'd3: tb_soc_manifest_scale.g_slv2.u_bus.u_bridge.bus_read_wait(handle, data, resp);
          default: begin
            data = 32'hDEADDEAD; resp = 2'd2;
            $fatal(1, "[BUS] bus_read_wait: unbound CPU_ID=%0d", CPU_ID);
          end
        endcase
