// Auto-generated by gen_tb_campaign.py — tb_soc_manifest bus_write_issue
        case (CPU_ID)
          7'd1: tb_soc_manifest.g_slv0.u_bus.u_bridge.bus_write_issue(addr, data, size, handle, ok);
          7'd2: tb_soc_manifest.g_slv1.u_bus.u_bridge.bus_write_issue(addr, data, size, handle, ok);
          7'd3: tb_soc_manifest.g_slv2.u_bus.u_bridge.bus_write_issue(addr, data, size, handle, ok);
          default: begin
            handle = -1; ok = 1'b0;
            $fatal(1, "[BUS] bus_*_issue: unbound CPU_ID=%0d", CPU_ID);
          end
        endcase
