// Auto-generated by gen_tb_campaign.py — chip_top_example bus_read_outstanding_count
        case (CPU_ID)
          7'd1: n = 0;
          7'd2: n = 0;
          7'd3: chip_top_example.g_slv2.u_bus.u_bridge.bus_read_outstanding_count(n);
          default: n = 0;
        endcase
