// Auto-generated by gen_tb_campaign.py — tb_soc_manifest bus_write_outstanding_count
        case (CPU_ID)
          7'd1: n = 0;
          7'd2: n = 0;
          7'd3: tb_soc_manifest.g_slv2.u_bus.u_bridge.bus_write_outstanding_count(n);
          default: n = 0;
        endcase
