// Auto-generated by gen_tb_campaign.py — tb_soc_manifest_scale bus_read bind
        case (CPU_ID)
          7'd1: tb_soc_manifest_scale.g_slv0.u_bus.u_bridge.bus_read(addr, size, data, resp);
          7'd2: tb_soc_manifest_scale.g_slv1.u_bus.u_bridge.bus_read(addr, size, data, resp);
          7'd3: tb_soc_manifest_scale.g_slv2.u_bus.u_bridge.bus_read(addr, size, data, resp);
          default: begin data = 32'h0; resp = 2'd2; end
        endcase
