// Auto-generated by gen_tb_campaign.py — tb_soc_manifest bus_read_poll
        case (CPU_ID)
          7'd1: tb_soc_manifest.g_slv0.u_bus.u_bridge.bus_read_poll(handle, data, resp, done);
          7'd2: tb_soc_manifest.g_slv1.u_bus.u_bridge.bus_read_poll(handle, data, resp, done);
          7'd3: tb_soc_manifest.g_slv2.u_bus.u_bridge.bus_read_poll(handle, data, resp, done);
          default: begin
            data = 32'hDEADDEAD; resp = 2'd2; done = 1'b0;
            $fatal(1, "[BUS] bus_read_poll: unbound CPU_ID=%0d", CPU_ID);
          end
        endcase
