/* Auto-generated by build_icode_pool.py — do not edit */
#ifndef ICODE_MAP_H
#define ICODE_MAP_H

#include <stdint.h>

#define ICODE_SLOT_SIZE    0x00001000u
#define ICODE_POOL_BASE    0x00001000u
#define ICODE_MAP_COUNT    50u
#define ICODE_POOL_BYTES   208896u

typedef struct {
    const char *name;
    uint32_t    pool_ptr;
    uint32_t    bus_addr;
    uint8_t     bus_op;     /* 'R' or 'W' */
    uint8_t     tap_port;
    uint16_t    bin_bytes;
} icode_map_entry_t;

static const icode_map_entry_t ICODE_MAP[] = {
    { "check_sfr_ctrl", 0x00001000u, 0x40000000u, 'R', 0, 20 },
    { "check_sfr_mask", 0x00002000u, 0x40000004u, 'R', 0, 20 },
    { "check_sram_aux", 0x00003000u, 0x80000004u, 'R', 1, 20 },
    { "check_sram_marker", 0x00004000u, 0x80000000u, 'R', 1, 20 },
    { "check_uart_baud", 0x00005000u, 0xC0000000u, 'R', 2, 20 },
    { "check_uart_irq", 0x00006000u, 0xC0000010u, 'R', 2, 20 },
    { "probe_sfr_r_008", 0x00007000u, 0x40000008u, 'R', 0, 20 },
    { "probe_sfr_r_00c", 0x00008000u, 0x4000000Cu, 'R', 0, 20 },
    { "probe_sfr_r_010", 0x00009000u, 0x40000010u, 'R', 0, 20 },
    { "probe_sfr_r_014", 0x0000A000u, 0x40000014u, 'R', 0, 20 },
    { "probe_sfr_r_018", 0x0000B000u, 0x40000018u, 'R', 0, 20 },
    { "probe_sfr_r_01c", 0x0000C000u, 0x4000001Cu, 'R', 0, 20 },
    { "probe_sfr_r_020", 0x0000D000u, 0x40000020u, 'R', 0, 20 },
    { "probe_sfr_r_024", 0x0000E000u, 0x40000024u, 'R', 0, 20 },
    { "probe_sfr_r_028", 0x0000F000u, 0x40000028u, 'R', 0, 20 },
    { "probe_sfr_r_02c", 0x00010000u, 0x4000002Cu, 'R', 0, 20 },
    { "probe_sfr_r_0fc", 0x00011000u, 0x400000FCu, 'R', 0, 20 },
    { "probe_sram_r_008", 0x00012000u, 0x80000008u, 'R', 1, 20 },
    { "probe_sram_r_00c", 0x00013000u, 0x8000000Cu, 'R', 1, 20 },
    { "probe_sram_r_010", 0x00014000u, 0x80000010u, 'R', 1, 20 },
    { "probe_sram_r_014", 0x00015000u, 0x80000014u, 'R', 1, 20 },
    { "probe_sram_r_018", 0x00016000u, 0x80000018u, 'R', 1, 20 },
    { "probe_sram_r_01c", 0x00017000u, 0x8000001Cu, 'R', 1, 20 },
    { "probe_sram_r_020", 0x00018000u, 0x80000020u, 'R', 1, 20 },
    { "probe_sram_r_024", 0x00019000u, 0x80000024u, 'R', 1, 20 },
    { "probe_sram_r_028", 0x0001A000u, 0x80000028u, 'R', 1, 20 },
    { "probe_sram_r_02c", 0x0001B000u, 0x8000002Cu, 'R', 1, 20 },
    { "probe_sram_w_000", 0x0001C000u, 0x80000000u, 'W', 1, 28 },
    { "probe_sram_w_004", 0x0001D000u, 0x80000004u, 'W', 1, 28 },
    { "probe_sram_w_008", 0x0001E000u, 0x80000008u, 'W', 1, 28 },
    { "probe_sram_w_00c", 0x0001F000u, 0x8000000Cu, 'W', 1, 28 },
    { "probe_sram_w_010", 0x00020000u, 0x80000010u, 'W', 1, 28 },
    { "probe_sram_w_014", 0x00021000u, 0x80000014u, 'W', 1, 28 },
    { "probe_sram_w_018", 0x00022000u, 0x80000018u, 'W', 1, 28 },
    { "probe_sram_w_01c", 0x00023000u, 0x8000001Cu, 'W', 1, 28 },
    { "probe_uart_r_004", 0x00024000u, 0xC0000004u, 'R', 2, 20 },
    { "probe_uart_r_008", 0x00025000u, 0xC0000008u, 'R', 2, 20 },
    { "probe_uart_r_00c", 0x00026000u, 0xC000000Cu, 'R', 2, 20 },
    { "probe_uart_r_014", 0x00027000u, 0xC0000014u, 'R', 2, 20 },
    { "probe_uart_r_018", 0x00028000u, 0xC0000018u, 'R', 2, 20 },
    { "probe_uart_r_01c", 0x00029000u, 0xC000001Cu, 'R', 2, 20 },
    { "probe_uart_r_020", 0x0002A000u, 0xC0000020u, 'R', 2, 20 },
    { "probe_uart_w_000", 0x0002B000u, 0xC0000000u, 'W', 2, 28 },
    { "probe_uart_w_004", 0x0002C000u, 0xC0000004u, 'W', 2, 28 },
    { "probe_uart_w_008", 0x0002D000u, 0xC0000008u, 'W', 2, 28 },
    { "probe_uart_w_00c", 0x0002E000u, 0xC000000Cu, 'W', 2, 28 },
    { "probe_uart_w_010", 0x0002F000u, 0xC0000010u, 'W', 2, 28 },
    { "probe_uart_w_014", 0x00030000u, 0xC0000014u, 'W', 2, 28 },
    { "probe_uart_w_018", 0x00031000u, 0xC0000018u, 'W', 2, 28 },
    { "probe_uart_w_01c", 0x00032000u, 0xC000001Cu, 'W', 2, 28 },
};

#endif /* ICODE_MAP_H */
