/* Auto-generated by build_icode_pool.py — do not edit */
#ifndef ICODE_MAP_H
#define ICODE_MAP_H

#include <stdint.h>

#define ICODE_SLOT_SIZE    0x00001000u
#define ICODE_POOL_BASE    0x00001000u
#define ICODE_MAP_COUNT    6u
#define ICODE_POOL_BYTES   28672u

typedef struct {
    const char *name;
    uint32_t    pool_ptr;
    uint32_t    bus_addr;
    uint8_t     bus_op;     /* 'R' or 'W' */
    uint8_t     tap_port;
    uint16_t    bin_bytes;
} icode_map_entry_t;

static const icode_map_entry_t ICODE_MAP[] = {
    { "check_sfr_ctrl", 0x00001000u, 0x40000000u, 'R', 0, 20 },
    { "check_sfr_mask", 0x00002000u, 0x40000004u, 'R', 0, 20 },
    { "check_sram_aux", 0x00003000u, 0x80000004u, 'R', 1, 20 },
    { "check_sram_marker", 0x00004000u, 0x80000000u, 'R', 1, 20 },
    { "check_uart_baud", 0x00005000u, 0xC0000000u, 'R', 2, 20 },
    { "check_uart_irq", 0x00006000u, 0xC0000010u, 'R', 2, 20 },
};

#endif /* ICODE_MAP_H */
