+incdir+../include/common
+define+MEM_SUBSYS
+define+DDR_CHANNELS=2
../rtl/mem/memory_subsystem.v
../rtl/leaves/ddr5_ctrl.v
../rtl/leaves/lpddr5_ctrl.v
../rtl/leaves/hbm2_stack.v
../rtl/leaves/sram_bank.v
../rtl/leaves/flash_ctrl.v
../rtl/leaves/nor_spi_mem.v
../rtl/leaves/emmc_host.v
