#!/usr/bin/env python3
"""Fan-out firmware/campaign/campaign_slots.yaml → derived integration views.

Edit ONLY campaign_slots.yaml (active[] + optional chip{}). Do not hand-edit:
  - soc_integration_ports.yaml
  - soc_hierarchy_from_slots.yaml

Run: make discover   (or automatically before make config)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:
    yaml = None  # type: ignore

from gen_campaign_config import SLOTS_YAML, resolve_addr
from verilog_paths import CAMPAIGN_ROOT

ROOT = Path(CAMPAIGN_ROOT)
OUT_INTEGRATION = ROOT / "soc_integration_ports.yaml"
OUT_HIERARCHY = ROOT / "soc_hierarchy_from_slots.yaml"
STAMP = ROOT / ".discover_stamp"

GENERATED_HEADER = """# AUTO-GENERATED by discover_campaign_slots.py — DO NOT EDIT
# SSOT: campaign_slots.yaml (active[]). Re-run: make discover
#
"""


def _addr_base(ent: dict[str, Any]) -> int:
    ab = ent.get("addr_base")
    if ab is not None and str(ab).strip() != "":
        return int(ab, 0) if isinstance(ab, str) else int(ab)
    targets = ent.get("targets") or []
    if targets:
        sym = targets[0].get("sym")
        if sym:
            return resolve_addr(str(sym))
    return 0


def _addr_size(ent: dict[str, Any]) -> int:
    az = ent.get("addr_size", 0x1000)
    return int(az, 0) if isinstance(az, str) else int(az)


def active_rows_for_integration(raw: dict[str, Any]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for ent in raw.get("active") or []:
        bus_port = str(ent.get("bus_port") or "").strip()
        if not bus_port:
            continue
        rows.append({
            "name": ent["name"],
            "role": ent.get("role", "generic"),
            "cpu_id": int(ent["cpu_id"]),
            "tap_port": int(ent.get("tap_port", ent["cpu_id"])),
            "bus_type": str(ent.get("bus_type", "task")),
            "bus_port": bus_port,
            "addr_base": f"0x{_addr_base(ent):08X}",
            "addr_size": f"0x{_addr_size(ent):08X}",
        })
    rows.sort(key=lambda r: r["cpu_id"])
    return rows


def soc_name_from(raw: dict[str, Any]) -> str:
    chip = raw.get("chip") or {}
    name = chip.get("soc_name") or raw.get("soc_name") or "integration_soc"
    return str(name).strip() or "integration_soc"


def write_integration_ports(raw: dict[str, Any], slaves: list[dict[str, Any]]) -> None:
    payload = {
        "soc_name": soc_name_from(raw),
        "slaves": slaves,
    }
    text = GENERATED_HEADER + yaml.safe_dump(payload, sort_keys=False, allow_unicode=True)
    OUT_INTEGRATION.write_text(text, encoding="utf-8")
    print(f"[discover] Wrote {OUT_INTEGRATION.name} ({len(slaves)} port(s))")


def write_hierarchy(raw: dict[str, Any], slaves: list[dict[str, Any]]) -> None:
    hier_slaves = []
    for s in slaves:
        hier_slaves.append({
            "name": s["name"],
            "cpu_id": s["cpu_id"],
            "tap_port": s["tap_port"],
            "bus_type": s["bus_type"],
            "bus_port": s["bus_port"],
            "addr_base": s["addr_base"],
            "addr_size": s["addr_size"],
        })
    payload = {"soc_name": soc_name_from(raw), "slaves": hier_slaves}
    text = GENERATED_HEADER + yaml.safe_dump(payload, sort_keys=False, allow_unicode=True)
    OUT_HIERARCHY.write_text(text, encoding="utf-8")
    print(f"[discover] Wrote {OUT_HIERARCHY.name}")


def load_raw(slots_path: Path) -> dict[str, Any]:
    if yaml is None:
        raise RuntimeError("PyYAML required: pip install pyyaml")
    if not slots_path.is_file():
        raise FileNotFoundError(slots_path)
    return yaml.safe_load(slots_path.read_text(encoding="utf-8")) or {}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--slots", type=Path, default=SLOTS_YAML, help="SSOT YAML (default: campaign_slots.yaml)")
    ap.add_argument("--skip-hierarchy", action="store_true")
    args = ap.parse_args()

    raw = load_raw(args.slots)
    slaves = active_rows_for_integration(raw)
    if not slaves:
        print(
            "[discover] ERROR: no active[] rows with bus_port — "
            "fix campaign_slots.yaml; not overwriting integration views",
            file=sys.stderr,
        )
        return 1

    write_integration_ports(raw, slaves)
    if not args.skip_hierarchy:
        write_hierarchy(raw, slaves)

    STAMP.write_text(f"slots={args.slots.name}\nports={len(slaves)}\n", encoding="utf-8")
    print(f"[discover] SSOT: {args.slots.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())