#!/usr/bin/env python3
"""Emit icode .c sources and icodes.mk for the current campaign manifest.

Default (example.sh gen): only icodes referenced in campaign_slots.yaml targets.
Optional regression: ICODE_CATALOG=full (or legacy =50) → full probe catalog.
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

CAMPAIGN_ROOT = Path(__file__).resolve().parent
ICODES_ROOT = CAMPAIGN_ROOT / "icodes"
PROBE_DIR = ICODES_ROOT / "probe"
MANIFEST_HDR = CAMPAIGN_ROOT / "include" / "campaign_manifest.h"
ICODES_MK = ICODES_ROOT / "icodes.mk"
TOOLS = CAMPAIGN_ROOT.parent.parent / "tools"
sys.path.insert(0, str(TOOLS))

from probe_icodes import (  # noqa: E402
    IcodeSpec,
    build_catalog_50,
    catalog_by_name,
    manifest_icode_names_hdr,
)

HAND_DIRS = ("sfr", "sram", "uart")


def emit_c(spec: IcodeSpec) -> str:
    if spec.op == "R":
        body = f"    bus_read32(11, 0x{spec.bus_addr:08X}u);\n    vstop();"
    else:
        body = (
            f"    load_soc_addr(5, 0x{spec.write_data:08X}u);\n"
            f"    bus_write32(5, 0x{spec.bus_addr:08X}u);\n"
            f"    vstop();"
        )
    return (
        '#include "icode.h"\n'
        "\n"
        f"ICODE_ENTRY({spec.name})\n"
        "{\n"
        f"{body}\n"
        "}\n"
    )


def discover_hand_written() -> dict[str, Path]:
    """Map icode name → .c path relative to icodes/ (hand-authored check_*)."""
    found: dict[str, Path] = {}
    for sub in HAND_DIRS:
        d = ICODES_ROOT / sub
        if not d.is_dir():
            continue
        for path in sorted(d.glob("*.c")):
            found[path.stem] = path.relative_to(ICODES_ROOT)
    return found


def _catalog_mode() -> bool:
    v = os.environ.get("ICODE_CATALOG", "").strip().lower()
    return v in ("50", "full", "1", "yes", "true")


def required_icode_names() -> list[str]:
    if _catalog_mode():
        return [s.name for s in build_catalog_50()]
    return manifest_icode_names_hdr(MANIFEST_HDR)


def _count_manifest_active_slots() -> int:
    if not MANIFEST_HDR.is_file():
        return 0
    from manifest_h_parser import parse_slave_rows

    body = MANIFEST_HDR.read_text(encoding="utf-8")
    return sum(1 for s in parse_slave_rows(body) if s.get("enabled"))


def resolve_spec(name: str, catalog: dict[str, IcodeSpec]) -> IcodeSpec:
    if name not in catalog:
        raise KeyError(
            f"icode '{name}' not in catalog-50 — add hand-written .c under icodes/ "
            f"or extend build_catalog_50() in tools/probe_icodes.py"
        )
    return catalog[name]


def main() -> int:
    catalog = catalog_by_name()
    hand = discover_hand_written()
    names = required_icode_names()
    mode = "catalog-full" if _catalog_mode() else "manifest"

    PROBE_DIR.mkdir(parents=True, exist_ok=True)

    sources: list[str] = []
    auto_gen: set[str] = set()
    written = 0

    for name in names:
        if name in hand:
            sources.append(hand[name].as_posix())
            continue
        spec = resolve_spec(name, catalog)
        auto_gen.add(name)
        rel = f"probe/{name}.c"
        sources.append(rel)
        path = ICODES_ROOT / rel
        text = emit_c(spec)
        if not path.exists() or path.read_text(encoding="utf-8") != text:
            path.write_text(text, encoding="utf-8")
            written += 1

    # Drop stale auto-generated probe sources not in this manifest
    pruned = 0
    for path in PROBE_DIR.glob("*.c"):
        if path.stem not in auto_gen:
            path.unlink()
            pruned += 1

    mk_lines = [
        "# Auto-generated by gen_icodes_c.py — do not edit",
        f"# Mode: {mode} ({len(names)} icode(s))",
        "ICODE_SOURCES := " + " ".join(sources),
        "",
    ]
    ICODES_MK.write_text("\n".join(mk_lines), encoding="utf-8")

    hand_used = sum(1 for n in names if n in hand)
    active_slots = _count_manifest_active_slots()
    print(
        f"[gen_icodes_c] mode={mode} manifest_active={active_slots} "
        f"icodes={len(names)} (hand={hand_used}, probe={len(auto_gen)}, "
        f"written={written}, pruned={pruned})"
    )
    for s in sources:
        print(f"  {s}")
    if mode == "manifest":
        print("[gen_icodes_c] tip: ICODE_CATALOG=full for full probe catalog regression build")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())