#!/usr/bin/env python3
"""Generate verif_soc_bus_connect.vh from manifest or soc_hierarchy YAML."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    yaml = None  # type: ignore

from amba_bus_registry import connect_invoke_macro, connect_slv_tag, normalize_bus_type
from verilog_paths import CAMPAIGN_ROOT, INCLUDE_DIR

ROOT = Path(CAMPAIGN_ROOT)
MANIFEST_HDR = ROOT / "include" / "campaign_manifest.h"
DEFAULT_YAML = ROOT / "soc_hierarchy_example.yaml"
OUT_VH = Path(INCLUDE_DIR) / "verif_soc_bus_connect.vh"

SLAVE_ROW_RE = re.compile(
    r'\{\s*"([^"]+)"\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*POOL_WORD_\w+\s*,\s*(\d+)\s*,\s*(\d+)'
    r'(?:\s*,\s*"([^"]*)"\s*,\s*"([^"]*)")?\s*\}'
)


def parse_manifest_h(path: Path) -> list[dict]:
    body = path.read_text(encoding="utf-8")
    slaves = []
    for m in SLAVE_ROW_RE.finditer(body):
        slaves.append({
            "name": m.group(1),
            "cpu_id": int(m.group(2)),
            "tap_port": int(m.group(3)),
            "enabled": int(m.group(5)),
            "bus_type": (m.group(6) or "task").lower(),
            "bus_port": m.group(7) or "",
        })
    m_present = re.search(r"#define\s+CAMPAIGN_MASTER_PRESENT\s+(\d+)", body)
    if m_present and int(m_present.group(1)):
        mm = re.search(
            r'static const manifest_master_t MANIFEST_MASTER = \{\s*'
            r'"([^"]+)"\s*,\s*0\s*,\s*(\d+)\s*,\s*POOL_WORD_MASTER\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*'
            r'"([^"]*)"\s*,\s*"([^"]*)"\s*,',
            body,
        )
        if mm and int(mm.group(4)):
            slaves.append({
                "name": mm.group(1),
                "cpu_id": 0,
                "tap_port": int(mm.group(2)),
                "enabled": 1,
                "bus_type": (mm.group(5) or "task").lower(),
                "bus_port": mm.group(6) or "",
            })
    return slaves


def parse_yaml(path: Path) -> list[dict]:
    if yaml is None:
        raise RuntimeError("PyYAML required: pip install pyyaml")
    raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    slaves = []
    for ent in raw.get("slaves") or []:
        slaves.append({
            "name": ent["name"],
            "cpu_id": int(ent["cpu_id"]),
            "tap_port": int(ent.get("tap_port", ent["cpu_id"])),
            "enabled": 1,
            "bus_type": str(ent.get("bus_type", "axi")).lower(),
            "bus_port": str(ent.get("bus_port", "") or ""),
        })
    return slaves


def emit_connect_vh(slaves: list[dict], source: str) -> str:
    lines = [
        "// Auto-generated by gen_soc_bus_connect.py — do not edit",
        f"// Source: {source}",
        "`ifndef VERIF_SOC_BUS_CONNECT_VH",
        "`define VERIF_SOC_BUS_CONNECT_VH",
        "",
        "`include \"verif_amba_connect_macros.vh\"",
        "",
    ]

    connect_calls: list[str] = []
    for s in slaves:
        bt = normalize_bus_type(str(s.get("bus_type", "task")))
        port = str(s.get("bus_port") or "").strip()
        if bt in ("task", "none") or not port:
            continue
        tag = connect_slv_tag(bt)
        macro_fn = connect_invoke_macro(bt)
        if not tag or not macro_fn:
            lines.append(f"// SKIP {s['name']}: bus_type {bt} has no connect macro")
            continue
        cid = s["cpu_id"]
        mst = "g_mstr.u_bus" if cid == 0 else f"g_slv{cid - 1}.u_bus"
        macro = f"CONNECT_SLV{cid:02d}_{tag}"
        conn = f"`{macro_fn}({port}, {mst})"
        lines.append(f"`define {macro} {conn}")
        lines.append(
            f"// {s['name']} cpu_id={cid} tap={s.get('tap_port')} bus_type={bt}"
        )
        connect_calls.append(f"  `ifdef CONNECT_SLV{cid:02d}_{tag}")
        connect_calls.append(f"    `CONNECT_SLV{cid:02d}_{tag};")
        connect_calls.append("  `endif")
        lines.append("")

    lines.append("// Apply all manifest-driven bus connects in your SoC top")
    lines.append("`define APPLY_ALL_SOC_BUS_CONNECTS \\")
    if connect_calls:
        lines.extend([ln + " \\" for ln in connect_calls[:-1]])
        lines.append(connect_calls[-1])
    else:
        lines.append("  /* no external bus ports in manifest */")
    lines.extend(["", "`endif", ""])
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate verif_soc_bus_connect.vh")
    ap.add_argument(
        "--yaml",
        type=Path,
        default=None,
        help=f"SoC hierarchy YAML (default: use {MANIFEST_HDR.name})",
    )
    args = ap.parse_args()

    if args.yaml:
        slaves = parse_yaml(args.yaml)
        source = str(args.yaml)
    else:
        if not MANIFEST_HDR.is_file():
            print(f"[bus_connect] missing {MANIFEST_HDR} — run make config", file=sys.stderr)
            return 1
        slaves = parse_manifest_h(MANIFEST_HDR)
        source = str(MANIFEST_HDR)

    text = emit_connect_vh(slaves, source)
    OUT_VH.parent.mkdir(parents=True, exist_ok=True)
    OUT_VH.write_text(text, encoding="utf-8")
    wired = sum(
        1 for s in slaves
        if normalize_bus_type(s.get("bus_type", "task")) not in ("task", "none")
        and s.get("bus_port")
    )
    print(f"[bus_connect] Wrote {OUT_VH} ({wired} external bus port(s))")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())