// VerifCPU include search paths
// Include with -f incdirs.f
// Generated by tools/gen_filelist.py — do not edit
// Paths relative to verif_cpu_verilog/ (package root)

+incdir+include
+incdir+firmware/campaign/include
